HAI 1.3

I HAS A NUM ITZ 0
IM IN YR INTS UPPIN YR NUM TIL BOTH SAEM NUM AN 3
	VISIBLE NUM
KTHX

NUM R 3, BTW this is already true
IM IN YR INTS NERFIN YR NUM WILE DIFFRINT NUM AN 0
	VISIBLE NUM
KTHX

NUM R 0
IM IN YR INTS UPPIN YR NUM
	BOTH SAEM NUM AN 3, O RLY?
		YA RLY, GTFO
		NO WAI, VISIBLE NUM, WHATEVER
	OIC
	VISIBLE "no"
KTHX

NUM R 3, BTW this is already true
I HAS A NOTHER
IM IN YR INTS NERFIN YR NUM
	NOTHER R 0
	IM IN YR OUTS UPPIN YR NOTHER WILE DIFFRINT NUM AN NOTHER
		NOTHER, DIFFRINT IT AN SMALLR OF IT AN NUM
		O RLY?
			YA RLY, GTFO INTS
		OIC
	KTHX
	VISIBLE NOTHER
KTHX

IM IN YR BOX
	GTFO
KTHX

KTHXBYE